### ISSUE TITLE
Error: Cannot find module 'is-npm'

### ISSUE THREAD

**Issue by khasky** [tnicola/cypress-parallel#9] opened 2020-08-03 19:31 UTC
Error while running command: 

`cypress-parallel -s cy:run -t 3 -d ./cypress/integration -a '\"--config baseUrl=https://domain.com\"'`

```
Error: Cannot find module 'is-npm'
Require stack:
- \cypress\node_modules\cypress-parallel\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (\cypress\node_modules\cypress-parallel\cli.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '\\cypress\\node_modules\\cypress-parallel\\cli.js'
  ]
}
```

**Comment by JohnnyFun** [comment] 2020-08-04 13:58
I got around this by just installing it, fwiw: `npm i -D is-npm`. But then ran into a path issue :(

**Comment by RiZKiT** [comment] 2020-08-06 13:06
Duplicate of #3

**Comment by tnicola** [comment] 2020-08-06 13:56
I'll check this. In the meanwhile you may need to wrap that command in a npm script command:

```
    "cy:run": "cypress run <your-params-if-any>",
    "cy:parallel": "cypress-parallel -s cy:run -t 3 -d ./cypress/integration -a '\"--config baseUrl=https://domain.com\"' '"
```

and then run:

`npm run cy:parallel`

**Closed** 2020-11-13 13:59 UTC
